app = "crypto-price-monitor"
primary_region = "sin"  # Singapore region, you can change this to a region closer to you

[build]
  dockerfile = "Dockerfile"

[env]
  # These will be overridden by secrets set with 'fly secrets set'
  # Do not put actual secrets here

[processes]
  app = "python app.py"

# Remove the http_service section since this app doesn't expose an HTTP port
# This is a background worker application, not a web service
